### ISSUE TITLE
New Issue for Seth

### ISSUE THREAD

**Issue by shariquemulla** [shariquemulla/PROG3017-boilerplate-test#3]
https://github.com/shariquemulla/PROG3017-boilerplate-test/blob/ecd7dc0817d00a2a819804b4df42bd4e5af527fb/client/src/App.tsx#L25

**Comment by sethmaclean** [comment]
{*/ Hey Sharique!, 
Received your message loud and clear. 
Everything looks good on this end... issue closed.
@sethmaclean /*}
